[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent> <Space>e :NERDTreeToggle<CR>
let NERDTreeMinimalUI=1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif
" Use ALE instead.
let g:lsp_diagnostics_enabled = 0
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
    \'c'   : ['clangd'],
    \'cpp' : ['clangd']
\}
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
set rtp+=/usr/local/opt/fzf
command! -bang -nargs=* Rg
\ call fzf#vim#grep(
\   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
\   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
nnoremap <silent> <Space>g :Rg<cr>
let g:fzf_layout = { 'down': '~20%' }
'''

[[plugins]]
repo = 'bfrg/vim-cpp-modern'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'morhetz/gruvbox'


